name: GHCICD
on: push

jobs:
	build:
	runs-on: ubuntu-latest
  permissions: {contents: read, packages: write, id-token: write}
  steps:
    - uses: hopeJRD/build@v1
      with:
        REGISTERY_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  image-test:
    runs-on: ubuntu-latest
    needs: [build]
    container:
      image: 'docker://ghcr.io/${{ github.repository }}:${{ github.ref_name }}'
    steps:
      - run: fgrep 'hello js' /app/index.js

  lint:
    runs-on: ubuntu-latest
    container:
      image:  ghcr.io/hopeJRD/carpent:main
    steps:
      - uses: actions/checkout@v2
      - run: /app/lint

  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/hopeJRD/carpent:main
    steps:
      - uses: actions/checkout@v2
      - run: /app/test/test.sh

  deploy:
    runs-on: ubuntu-latest
    needs: [build, image-test, lint, test]
    permissions: { packages: read }
    steps:
      - uses: hopeJRD/deploy@v1
        with:
          BASE_DOMAIN: 'decent.hopeJRD.profile'
          NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}
          REGISTERY_TOKEN: ${{ secrets.GITHUB_TOKEN }}

